<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var Sqala\Payment\Block\Order\Success\Additional $block
 */
$qrCode = $block->getQrCode();
?>
<div class="sqala-payment-success-details">
    <div>
        <p>
            <?= $escaper->escapeHtml(__('To pay, please scan the QR code')) ?>
        </p>
        <div style="display:flex;margin-bottom:25px;">
            <div id="qrcode" style="margin-right:30px"></div>
            <div class="field sqala-input-group">
                <div class="control _with-tooltip">
                    <textarea id="qr-code-value" rows="6" cols="30" readonly><?= $escaper->escapeHtml($qrCode) ?></textarea>
                    <button id="copy-pix-code" class="action submit primary"><?=$escaper->escapeHtml(__('Copy'));?></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require([
        'Sqala_Payment/js/qrcode.min',
        'jquery'
    ], function (_, $) {
        var QR_CODE = new QRCode("qrcode", {
            width: 220,
            height: 220,
            colorDark: "#000000",
            colorLight: "#ffffff",
            correctLevel : QRCode.CorrectLevel.L,
        });
        QR_CODE.makeCode('<?= $escaper->escapeJs($qrCode) ?>');

        $('#copy-pix-code').on('click', function () {
            var $textarea = $('#qr-code-value');
            $textarea.select();
            document.execCommand('copy');

            $(this).text('<?= $escaper->escapeJs(__('Copied!')) ?>');
            setTimeout(() => {
                $('#copy-pix-code').text('<?= $escaper->escapeJs(__('Copy')) ?>');
            }, 1500);
        });
    })
</script>
